# Generated by Django 5.2.6 on 2025-09-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_emergencysection'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('Title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=100)),
                ('Mission', models.CharField(max_length=255)),
                ('Vission', models.CharField(max_length=255)),
                ('Doctors', models.URLField(blank=True, null=True)),
                ('Awards', models.URLField(blank=True, null=True)),
                ('Departments', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
