# Generated by Django 5.2.6 on 2025-09-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='Awards',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='Departments',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='Doctors',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
