# Generated by Django 5.2.6 on 2025-09-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_about_awards_alter_about_departments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='Awards',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='Departments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='Doctors',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
