# Generated by Django 5.2.6 on 2025-09-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_about_image_about_research_labs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Why_Choose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('description', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
