# Generated by Django 5.2.6 on 2025-09-09 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='Facebook',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='departments',
            name='Instagram',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='departments',
            name='Linkedin',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='departments',
            name='Twitter',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
