# Generated by Django 5.2.6 on 2025-09-09 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_departments_facebook_departments_instagram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='departments/')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('Twitter', models.CharField(blank=True, max_length=150)),
                ('Facebook', models.CharField(blank=True, max_length=150)),
                ('Instagram', models.CharField(blank=True, max_length=150)),
                ('Linkedin', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='departments',
            name='Facebook',
        ),
        migrations.RemoveField(
            model_name='departments',
            name='Instagram',
        ),
        migrations.RemoveField(
            model_name='departments',
            name='Linkedin',
        ),
        migrations.RemoveField(
            model_name='departments',
            name='Twitter',
        ),
    ]
