# Generated by Django 5.2.6 on 2025-09-09 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_doctor_remove_departments_facebook_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='Facebook',
            new_name='facebook',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='Instagram',
            new_name='instagram',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='Linkedin',
            new_name='linkedin',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='Twitter',
            new_name='twitter',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='description',
        ),
        migrations.AddField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='home.departments'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(upload_to='doctors/'),
        ),
    ]
