# Generated by Django 5.2.6 on 2025-09-09 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usp',
            old_name='description',
            new_name='Answer',
        ),
        migrations.RenameField(
            model_name='usp',
            old_name='title',
            new_name='Question',
        ),
    ]
