# Generated by Django 5.2.6 on 2025-09-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_description_usp_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(blank=True, max_length=100)),
                ('Answer', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.RenameField(
            model_name='usp',
            old_name='Answer',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='usp',
            old_name='Question',
            new_name='title',
        ),
    ]
