# Generated by Django 5.2.6 on 2025-09-09 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='company',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='header_footer_color',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='testmonial_bg',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='text_color',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='youtube',
        ),
    ]
