# Generated by Django 5.2.6 on 2025-09-09 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_setting_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='status',
        ),
    ]
