# Generated by Django 5.0.1 on 2025-09-26 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_appointment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='MediaGallery',
        ),
    ]
